export  const data=[
    {id:Math.random(),name:"Lucerne",info:"In a country of picture-perfect lakeside cities, it doesn’t get much more impressive than Lucerne. Surrounded by three large mountains, the compact medieval city sits on the shores of Lake Lucerne. Wandering around the captivating old town, you’ll be forgiven for thinking you’ve stepped into a painting. There’s ancient churches, bustling squares and plenty of boutiques to explore as you marvel at the architectural wonder of the city. But the highlight is the Chapel Bridge, a covered wooden bridge that has been connecting the center of Lucerne since 1333.",image:"https://www.expatica.com/app/uploads/sites/9/2014/05/luzern-1024x683.jpg",price:90},
{id:Math.random(),name:"Lake Geneva",info:"Stretching from Geneva in the west to Lausanne in the east, Lake Geneva is one of Switzerland’s most beautiful places. From the international bustle of Geneva to the many vineyards that crawl up the hillsides around the lake, there’s plenty to do in the surrounding region. And there’s a lot of activity on the lake, too. Windsurfing, water skiing, and kayaking are all possible for more active visitors to the area. Or, if you’re feeling a little lazier, you can simply sit back and take in the beauty of the lake from the deck of a paddle steamer as it crosses the water. ",image:"https://www.expatica.com/app/uploads/sites/9/2014/05/lakegeneva-1024x683.jpg",price:160},
{id:Math.random(),name:"Berlin's Brandenburg Gate",info:"Modeled on the Acropolis in Athens and built for King Frederick William II in 1791, the monumental sandstone Brandenburg Gate in Berlin's Mitte district was the city's first Neoclassical structure. It measures an impressive 26 meters in height, including the Quadriga,  ",image:"https://www.planetware.com/photos-large/D/germany-brandenburg-gate.jpg",price:60},
{id:Math.random(),name:"Swisse",info:"No trip to the Swiss Riviera is complete without checking out the medieval Château de Chillon. Located on an island in Lake Geneva near the popular town of Montreux, the castle dates back to the 10th century, when it was used as a strategic water fort. It then became a lakeside summer home for the wealthy Counts of Savoy, ",image:"https://www.expatica.com/app/uploads/sites/9/2014/05/matterhorn-1024x683.jpg",price:50},
{id:Math.random(),name:"Austria",info:"Tucked in between the soaring Alps, Austria is an enchanting country with dream-like landscapes, picture-perfect meadows and grasslands, stunning baroque architecture and music flowing through its veins.From pretty villages to magnificent cities, from the best operas to the most lavish desserts Austria has the perfect ingredients to intoxicate your senses. ",image:"https://img.traveltriangle.com/blog/wp-content/uploads/2018/05/Salzkammergut-cover.jpg",price:30},
{id:Math.random(),name:"Château de Chillon",info:"No trip to the Swiss Riviera is complete without checking out the medieval Château de Chillon. Located on an island in Lake Geneva near the popular town of Montreux, the castle dates back to the 10th century, when it   ",image:"https://www.expatica.com/app/uploads/sites/9/2014/05/chillon-1024x683.jpg",price:130},

]
// {id:Math.random(),name:"Jungfraujoch",info:" The Jungfraujoch is an Alpine wonderland that fully deserves its nickname of the “Top of Europe”. Technically a glacier saddle between two mountains, the Jungfraujoch is one the best – and highest – attractions in Switzerland. And don’t let the altitude put you off – there’s plenty for the whole family up there, from mountain climbing to tobogganing and much more. However, perhaps the most impressive attraction is the world-famous Jungfrau railway. Starting at Kleine Scheidegg, the train climbs up to 3,454 meters above sea level to Jungfraujoch, the highest railway station in Europe",image:"https://www.expatica.com/app/uploads/sites/9/2014/05/jungfrau-1024x683.jpg",price:230},
